//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHackerRankTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class myText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZHackerRankTests.TestSupport.myText", typeof(myText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///70 1988
        ///30 32
        ///50 9
        ///7 58
        ///50 66
        ///38 13
        ///31 67
        ///2 30
        ///14 46
        ///54 34
        ///10 7
        ///25 66
        ///20 18
        ///1 21
        ///49 63
        ///39 20
        ///55 5
        ///3 66
        ///58 34
        ///19 12
        ///43 62
        ///16 1
        ///10 11
        ///16 70
        ///11 35
        ///22 13
        ///16 2
        ///59 41
        ///29 45
        ///53 47
        ///43 59
        ///46 32
        ///64 65
        ///70 11
        ///4 11
        ///69 10
        ///21 41
        ///17 56
        ///49 63
        ///27 50
        ///30 23
        ///49 19
        ///45 46
        ///1 64
        ///67 58
        ///37 38
        ///33 68
        ///55 67
        ///35 5
        ///70 44
        ///14 26
        ///50 17
        ///4 10
        ///43 7
        ///15 44
        ///2 50
        ///64 28
        ///8 19
        ///7 31
        ///30 3
        ///36 59
        ///36 57
        ///27 60
        ///54 28
        ///26 69
        ///57 54
        ///49 20
        ///66 9
        ///44 41
        ///22 5
        ///46 10
        ///54 19
        ///13 3
        ///13 2
        ///49 1
        ///34 29 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bfs_input {
            get {
                return ResourceManager.GetString("bfs_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 6 6 6 12 6 12 6 12 12 6 6 6 6 6 12 12 6 6 6 6 12 6 12 6 12 6 12 12 12 12 6 12 12 6 12 12 6 12 6 12 6 12 12 6 6 12 6 6 6 6 12 12 12 12 6 6 6 12 6 6 12 12 12 12 12 12 6 6.
        /// </summary>
        internal static string bfs_output {
            get {
                return ResourceManager.GetString("bfs_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 625
        ///800 911324978
        ///722004653 422841575 1754347026 1268413156 1473882809 1159578250 1530954015 864433040 1429795835 446639653 1456334267 1839516330 2068337890 1717436812 1339403205 1950189949 935504206 276721350 551949780 232859945 1740272925 856190207 1928885286 1877378581 1413978977 737603307 347450411 610395285 257883982 638516573 1521720262 979888635 1061358147 1128583639 100818142 387757307 140678240 1631772156 1252190346 1570474075 2078411808 561040965 1262506756 1999266049 130994128 454426313 180197235 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maxmod_input06 {
            get {
                return ResourceManager.GetString("maxmod_input06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 911323095
        ///1077818923
        ///610823573
        ///47800459
        ///1921382181
        ///1556079396
        ///2003043015
        ///681118606
        ///386161441
        ///173999099
        ///1888839733
        ///773319624
        ///491558847
        ///521966962
        ///1255419509
        ///252944361
        ///426020741
        ///1446799556
        ///241120802
        ///489925853
        ///574424974
        ///1022327490
        ///341954250
        ///2046734835
        ///1697313963
        ///702217811
        ///39898412
        ///161479641
        ///634832594
        ///254575251
        ///66430599
        ///1174521694
        ///863138810
        ///590864761
        ///588755629
        ///113642111
        ///1665655675
        ///901877262
        ///1530624898
        ///1557663911
        ///1190574403
        ///725063263
        ///193290410
        ///2056233463
        ///682111814
        ///509614746
        ///118892272
        ///1086285597
        ///1306500337
        ///1471455 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maxmod_output06 {
            get {
                return ResourceManager.GetString("maxmod_output06", resourceCulture);
            }
        }
    }
}
